#
# makefile for OpenWrt (CROSS MIPSEL)
#
#


OPTFLAGS=-march=mips32r2 -mtune=1004kc -O -s

ALLFLAGS=${OPTFLAGS} -pipe \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=mipsel-openwrt-linux-musl-g++
CC=mipsel-openwrt-linux-musl-gcc
CC_SHARED=-fPIC -DPIC
LINK_SHARED=-fPIC -DPIC -shared

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

OBJ_CRC32=$(OBJ_CRC32_C)
OBJ_AES=

