#!/bin/sh /etc/rc.common
# Copyright (C) 2016-2018 OpenWrt.org

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/smtpd

start_service() {
	mkdir -p -m 0700 /var/empty
	mkdir -p -m 711 /var/spool/smtpd
	procd_open_instance
	procd_set_param command ${PROG} -d
	procd_close_instance
}

